
const types = {
  ADD_TO_CART: "ADD_TO_CART",
  DELETE_FROM_CART: "DELETE_FROM_CART",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
  SELECT_PAYMENT_TYPE: "SELECT_PAYMENT_TYPE",
  SELECT_ADDRESS: "SELECT_ADDRESS",
  DELETE_ADDRESS: "DELETE_ADDRESS",
  SELECT_CREDIT_CARD: "SELECT_CREDIT_CARD",
  CLEAR_CART: "CLEAR_CART",
  SET_SHIPPING: "SET_SHIPPING",
  SET_DESCRIPTION: "SET_DESCRIPTION"
}

export default types
