
const types = {
  ADD_TO_CART: "ADD_TO_CART",
  DELETE_FROM_CART: "DELETE_FROM_CART",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
  SELECT_PAYMENT_TYPE: "SELECT_PAYMENT_TYPE",
  SELECT_ADDRESS: "SELECT_ADDRESS",
  SELECT_CREDIT_CARD: "SSELECT_CREDIT_CARDELECT_ADDRESS",
}

export default types
