export const USER_SIGN_IN = "USER_SIGN_IN";
export const USER_SIGN_UP = "USER_SIGN_UP";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_RECOVER_PASSWORD = "USER_RECOVER_PASSWORD";
export const USER_RECOVER_PASSWORD_CALLBACK = "USER_RECOVER_PASSWORD_CALLBACK";